# Generated by Django 4.1.7 on 2023-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brickwork', models.TextField(max_length=500)),
                ('concrete', models.TextField(max_length=500)),
                ('waterproofing', models.TextField(max_length=500)),
                ('roofing', models.TextField(max_length=500)),
                ('stucco', models.TextField(max_length=500)),
            ],
        ),
    ]
