# Generated by Django 4.1.7 on 2023-03-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='brickwork',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='concrete',
            new_name='typeofwork',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='roofing',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stucco',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='waterproofing',
        ),
        migrations.CreateModel(
            name='Manywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('img', models.TextField(max_length=500)),
                ('desc', models.TextField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projects')),
            ],
        ),
    ]
