# Generated by Django 4.1.7 on 2023-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_brickwork_projects_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Inquiries',
            field=models.CharField(max_length=500),
        ),
    ]
