# Generated by Django 4.1.7 on 2023-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customer_inquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Inquiries',
            field=models.TextField(max_length=500),
        ),
    ]
