# Generated by Django 4.1.7 on 2023-03-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customer_inquiries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['typeofwork']},
        ),
        migrations.AlterField(
            model_name='manywork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='main_app.projects'),
        ),
    ]
