# Generated by Django 4.1.7 on 2023-03-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_customer_options_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Inquiries',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='subject',
        ),
    ]
